name: "Dev.to sync"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    name: "Sync posts"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish articles on dev.to
        uses: sinedied/publish-devto@v2
        with:
          # Your dev.to personal API key to publish and update articles.
          # See https://docs.dev.to/api/#section/Authentication/api_key
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          # Your GitHub personal access token, used to create commits for updated files.
          # If you have a protected branch, you need to use a personal access token
          # with the 'repo' permission.
          # See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # (Optional) The files to publish. Default is "posts/**/*.md"
          files: '_posts/**/*.md'
          # (Optional) The git branch to use. Default is 'main'.
          branch: main
          # (Optional) Use conventional commit messages. Default is false.
          # See https://www.conventionalcommits.org.
          conventional_commits: false
          # (Optional) Do not make actual changes on dev.to.
          dry_run: false
